// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJob(id) {
    return $Call.ByID(1245916576, id);
}

/**
 * @returns {$CancellablePromise<$models.Job[]>}
 */
export function GetJobs() {
    return $Call.ByID(2795355898).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} company
 * @param {string} role
 * @returns {$CancellablePromise<number>}
 */
export function SaveJob(company, role) {
    return $Call.ByID(3923482130, company, role);
}

/**
 * @param {number} id
 * @param {string} company
 * @param {string} role
 * @returns {$CancellablePromise<void>}
 */
export function UpdateJob(id, company, role) {
    return $Call.ByID(1878109278, id, company, role);
}

// Private type creation functions
const $$createType0 = $models.Job.createFrom;
const $$createType1 = $Create.Array($$createType0);
