// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function AddAvailableStage(name) {
    return $Call.ByID(3927907374, name);
}

/**
 * @param {number} jobId
 * @param {string} stage
 * @returns {$CancellablePromise<void>}
 */
export function AddJobStage(jobId, stage) {
    return $Call.ByID(1679456146, jobId, stage);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAvailableStage(name) {
    return $Call.ByID(2535730274, name);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJob(id) {
    return $Call.ByID(1245916576, id);
}

/**
 * @returns {$CancellablePromise<$models.StageMetadata[]>}
 */
export function GetAvailableStages() {
    return $Call.ByID(1567522294).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Job[]>}
 */
export function GetJobs() {
    return $Call.ByID(2795355898).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SankeyData | null>}
 */
export function GetSankeyData() {
    return $Call.ByID(3209808103).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} groupBy
 * @returns {$CancellablePromise<$models.TimelineData | null>}
 */
export function GetTimelineData(groupBy) {
    return $Call.ByID(432288241, groupBy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetAvailableStages() {
    return $Call.ByID(837502475);
}

/**
 * @param {$models.Job} j
 * @returns {$CancellablePromise<number>}
 */
export function SaveJob(j) {
    return $Call.ByID(3923482130, j);
}

/**
 * @param {$models.Job} j
 * @returns {$CancellablePromise<void>}
 */
export function UpdateJob(j) {
    return $Call.ByID(1878109278, j);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WipeDatabase() {
    return $Call.ByID(1458813272);
}

// Private type creation functions
const $$createType0 = $models.StageMetadata.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Job.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SankeyData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.TimelineData.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
