// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("company" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["company"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}
